countries_to_visit = ['USA','Norway','Denmark','Germany']
print(countries_to_visit)
print(sorted(countries_to_visit))
print(countries_to_visit)
print(sorted(countries_to_visit,reverse=True))
print(countries_to_visit)
countries_to_visit.reverse()
print(countries_to_visit)
countries_to_visit.reverse()
print(countries_to_visit)
countries_to_visit.sort()
print(countries_to_visit)
countries_to_visit.sort(reverse=True)
print(countries_to_visit)