guests = ['Dean','Sam','Diana']
print('------------------------------------------------------------------------------')
print('Hi, ' + guests[0] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[1] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[2] + '. You are welcome to have dinner with us on Thursday night.')
print('------------------------------------------------------------------------------')
print('Sorry! ' + guests[2] + ' won\'t be able to make it.')
guests[2] = 'Betty'
print('------------------------------------------------------------------------------')
print('Hi, ' + guests[0] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[1] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[2] + '. You are welcome to have dinner with us on Thursday night.')
print('------------------------------------------------------------------------------')
print('Hi, Guys. There\'s a change of location. We need a bigger place as more people will be joining us.')
guests.insert(0,'Jim')
guests.insert(2,'Aurora')
guests.append('Arthur')
print('------------------------------------------------------------------------------')
print('Hi, ' + guests[0] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[1] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[2] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[3] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[4] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[5] + '. You are welcome to have dinner with us on Thursday night.')
print('------------------------------------------------------------------------------')
print('Hi. It seems someone booked the new location before us.\nAnd unfortunately we have cancelled our reservations at the previous location.\nA new location that\'s available won\'t be able to fit all of us')
print('------------------------------------------------------------------------------')
print('Sorry, ' + guests.pop() + '. We won\'t be able to accomodate you.')
print('Sorry, ' + guests.pop() + '. We won\'t be able to accomodate you.')
print('Sorry, ' + guests.pop() + '. We won\'t be able to accomodate you.')
print('Sorry, ' + guests.pop() + '. We won\'t be able to accomodate you.')
print('------------------------------------------------------------------------------')
print('Hi, ' + guests[0] + '. You are still welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[1] + '. You are still welcome to have dinner with us on Thursday night.')
print('------------------------------------------------------------------------------')
del guests[0]
del guests[0]
print(guests)