guests = ['Dean','Sam','Diana']
print('------------------------------------------------------------------------------')
print('Hi, ' + guests[0] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[1] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[2] + '. You are welcome to have dinner with us on Thursday night.')
print('------------------------------------------------------------------------------')
print('Sorry! ' + guests[2] + ' won\'t be able to make it.')
guests[2] = 'Betty'
print('------------------------------------------------------------------------------')
print('Hi, ' + guests[0] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[1] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[2] + '. You are welcome to have dinner with us on Thursday night.')
print('------------------------------------------------------------------------------')
print('Hi, Guys. There\'s a change of location. We need a bigger place as more people will be joining us.')
guests.insert(0,'Jim')
guests.insert(2,'Aurora')
guests.append('Arthur')
print('------------------------------------------------------------------------------')
print('Hi, ' + guests[0] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[1] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[2] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[3] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[4] + '. You are welcome to have dinner with us on Thursday night.')
print('Hi, ' + guests[5] + '. You are welcome to have dinner with us on Thursday night.')
print('------------------------------------------------------------------------------')